### ISSUE TITLE
Request for ROS2 branches

### ISSUE THREAD

**Issue by Karsten1987** [ros-drivers/urg_c#10]
I would like to request the creation of branches for ROS2 development.
In particular, I am interested in having a `dashing-devel` and general `ros2-devel`. We have to port for `urg_c` available for dashing under [here](https://github.com/bosch-robotics-na/urg_c/tree/ros2-devel) and would like to open a PR to a ROS2 branch on this upstream repo and have it released from here ideally.

**Comment by tonybaltovski** [comment]
@Karsten1987 added the requested branches!

**Comment by Karsten1987** [comment]
thanks a lot :)
