### ISSUE TITLE
Release urg_c into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-drivers/urg_c#12]
Would you mind releasing `urg_c` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 16 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by tonybaltovski** [comment]
Released https://github.com/ros/rosdistro/pull/25191
